"""Generate the Lorient / Keroman map assets into Import/Lorient.

    python3 Tools/generate-lorient.py

Requires Python 3.10+ with numpy, scipy, pillow, shapely and mapbox_earcut
(pip install numpy scipy pillow shapely mapbox_earcut). The generated files are committed:
regeneration is optional. Content/Python/populate_lorient.py imports them into Unreal.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / "lorient"))

import numpy as np  # noqa: E402

import geography as g  # noqa: E402
import structures  # noqa: E402
import terrain  # noqa: E402
import textures  # noqa: E402
from meshkit import Mesh  # noqa: E402

OUT = HERE.parent / "Import" / "Lorient"


def groix():
    """Distant silhouette of the Ile de Groix: a 40 m plateau with cliffs, 100 m grid."""
    gr = g.GROIX
    m = Mesh("LorientGroix", tile=50.0)
    th = math.radians(gr["bearing"])
    f = np.array([math.sin(th), math.cos(th)])
    r = np.array([f[1], -f[0]])
    s = np.linspace(-0.6, 0.6, 61)
    A, B = np.meshgrid(s * gr["length"], s * gr["width"])
    ell = np.hypot(A / (gr["length"] / 2), B / (gr["width"] / 2))
    ell += 0.08 * np.sin(A / 300) * np.cos(B / 240)
    H = gr["cliff"] * g.smooth((1.0 - ell) * 18) + 12 * g.smooth((0.8 - ell) * 3) * g.fbm(A, B, 900, 3, 9) - 6
    E = gr["center"][0] + A * f[0] + B * r[0]
    N = gr["center"][1] + A * f[1] + B * r[1]
    P = np.stack([E, N, H], -1)
    tris = []
    for j in range(len(s) - 1):
        for i in range(len(s) - 1):
            a, b, c, d = P[j, i], P[j, i + 1], P[j + 1, i + 1], P[j + 1, i]
            tris += [[a, b, c], [a, c, d]]
    tris = np.array(tris)
    # Keep the winding facing up whatever the frame's handedness.
    n = np.cross(tris[:, 1] - tris[:, 0], tris[:, 2] - tris[:, 0])
    tris[n[:, 2] < 0] = tris[n[:, 2] < 0][:, ::-1]
    m.add(tris)
    return m


def ue(e, n, z=0.0):
    """ENU metres to Unreal centimetres (X east, Y south, Z up)."""
    return [round(e * 100, 1), round(-n * 100, 1), round(z * 100, 1)]


def yaw(bearing):
    return round(((bearing - 90) + 180) % 360 - 180, 2)


def layout(kit):
    e, n, bearing = g.player_start()
    goals = [
        dict(name="Appareillage : sortir de l'alveole K3", enu=g.S(250, 0), depth=0),
        dict(name="Passe de Port-Louis, sous la citadelle", enu=(100.0, -2150.0), depth=0),
        dict(name="Plongee d'essai au large de Gavres", enu=(-500.0, -5300.0), depth=20),
    ]
    props = []
    for p in kit.props:
        z = -1.90 if p["afloat"] else p["keel"] + 3.02   # VIIC mesh: waterline 1.90 m, keel -3.02 m
        props.append(dict(label=p["label"], location=ue(p["e"], p["n"], z), yaw=yaw(p["bearing"])))
    return dict(
        frame="Unreal cm: X east, Y south, Z up; origin on the quay in front of Keroman III (about 47.7275 N, 3.3685 W)",
        player=dict(location=ue(e, n, -1.90), yaw=yaw(bearing)),
        goals=[dict(name=gl["name"], location=ue(*gl["enu"], -gl["depth"])) for gl in goals],
        play_area=dict(center=ue(0, -2000), radius_cm=420000),
        viic_props=props,
        labels=[dict(name=nm, location=ue(p[0], p[1], z)) for nm, p, z in kit.labels],
        extent_m=g.EXTENT,
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-textures", action="store_true")
    args = ap.parse_args()
    t0 = time.time()
    mesh, field, height_at = terrain.build()
    kit, stats = structures.build(height_at, field)
    OUT.mkdir(parents=True, exist_ok=True)
    report = dict(generator="Tools/generate-lorient.py", meshes={}, stats=stats)
    for m in [mesh, groix(), *kit.meshes()]:
        path = OUT / f"{m.name}.obj"
        tris, verts = m.write_obj(path, f"{m.name} - Lorient / Keroman 1943, generated by Tools/generate-lorient.py")
        lo, hi = m.bounds()
        report["meshes"][m.name] = dict(triangles=int(tris), vertices=int(verts), min_m=np.round(lo, 2).tolist(),
                                        max_m=np.round(hi, 2).tolist(), md5=hashlib.md5(path.read_bytes()).hexdigest())
        print(f"{path.name}: {tris} triangles")
    lay = layout(kit)
    (OUT / "layout.json").write_text(json.dumps(lay, indent=1, ensure_ascii=False))
    if not args.skip_textures:
        tex = OUT / "Textures"
        tex.mkdir(exist_ok=True)
        textures.build_all(tex)
        color, mask = terrain.landcover(height_at, towns=g.TOWNS)
        color.save(tex / "T_LorientLandcover_D.jpg", quality=90)
        mask.resize((2048, 2048)).save(tex / "T_LorientLandcover_M.png", optimize=True)
    report["seconds"] = round(time.time() - t0, 1)
    (OUT / "generation-report.json").write_text(json.dumps(report, indent=1))
    print(json.dumps(stats), f"{report['seconds']} s")


if __name__ == "__main__":
    main()
